/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.util.Calendar;

import javax.swing.*;

import dao.ProductDao;

/**
 *
 * @author larry
 */

@SuppressWarnings({ "unchecked", "rawtypes" })
public class ManageProductView extends JDialog {
	
	private ProductDao pr_model;

	// Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel descriptionLabel;
    private JScrollPane descriptionScrollPane;
    private JTextArea descriptionTextArea;
    private JComboBox genreBox;
    private JLabel genreLabel;
    private JLabel headerLabel;
    private JComboBox ratingBox;
    private JLabel ratingLabel;
    private JButton resetButton;
    private JButton submitButton;
    private JButton editButton;
    private JTextField titleField;
    private JLabel titleLabel;
    private JComboBox typeBox;
    private JLabel typeLabel;
    private JComboBox yearBox;
    private JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Creates new form ManageProductView
     */
    public ManageProductView(java.awt.Frame parent, boolean modal, ProductDao model) {
        super(parent, modal);
        initComponents();
    }
    
    //Methods to return the text of the fields 
    public JLabel getHeaderLabel(){
    	return headerLabel;
    }
    
    public JTextField getTitleField(){
    	return titleField;
    }
    
    public JTextArea getDescription(){
    	return descriptionTextArea;
    }
    
    public JComboBox getYearBox(){
    	return yearBox;
    }
    
    public JComboBox getGenreBox(){
    	return genreBox;
    }
    
    public JComboBox getRatingBox(){
    	return ratingBox;
    }
    
    public JComboBox getTypeBox(){
    	return typeBox;
    }
    
    public JButton getSubmitButton(){
    	return submitButton;
    }
    
    public JButton getResetButton(){
    	return resetButton;
    }
    
    public JButton getEditButton(){
    	return editButton;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        descriptionScrollPane = new JScrollPane();
        descriptionTextArea = new JTextArea();
        typeLabel = new JLabel();
        ratingLabel = new JLabel();
        descriptionLabel = new JLabel();
        yearLabel = new JLabel();
        genreLabel = new JLabel();
        titleField = new JTextField();
        yearBox = new JComboBox();
        ratingBox = new JComboBox();
        titleLabel = new JLabel();
        genreBox = new JComboBox();
        headerLabel = new JLabel();
        resetButton = new JButton();
        submitButton = new JButton();
        editButton = new JButton();
        typeBox = new JComboBox();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Movie");

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        descriptionScrollPane.setViewportView(descriptionTextArea);

        typeLabel.setText("Type");

        ratingLabel.setText("Rating");

        descriptionLabel.setText("Description");

        yearLabel.setText("Year");

        genreLabel.setText("Genre");

        yearBox.setModel(new DefaultComboBoxModel(populateYears()));

        ratingBox.setModel(new DefaultComboBoxModel(populateRatings()));

        titleLabel.setText("Title");

        genreBox.setModel(new DefaultComboBoxModel(populateGenres()));

        headerLabel.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        headerLabel.setHorizontalAlignment(SwingConstants.CENTER);
        headerLabel.setText("Add New Movie");

        resetButton.setText("Reset");

        submitButton.setText("Add Movie");
        
        editButton.setText("Edit Movie");
        editButton.setEnabled(false);
        editButton.setVisible(false);

        typeBox.setModel(new DefaultComboBoxModel(populateTypes()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(headerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(descriptionLabel)
                    .addComponent(descriptionScrollPane)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLabel)
                            .addComponent(genreLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(yearLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yearBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(genreBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(ratingLabel)
                                .addGap(11, 11, 11)
                                .addComponent(ratingBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(typeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(submitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(headerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel)
                    .addComponent(yearLabel)
                    .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genreLabel)
                    .addComponent(ratingLabel)
                    .addComponent(genreBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ratingBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeLabel)
                    .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(editButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetButton)
                    .addComponent(submitButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>
    
    public void addSubmitButtonListener(ActionListener submit) {
        submitButton.addActionListener(submit);
    }
    
    public void addResetButtonListener(ActionListener reset) {
        resetButton.addActionListener(reset);
    }
    
    public void addEditButtonListener(ActionListener edit) {
        editButton.addActionListener(edit);
    }
    
    public void reset() {
    	titleField.setText("");
    	yearBox.setSelectedIndex(0);
    	genreBox.setSelectedIndex(0);
    	ratingBox.setSelectedIndex(0);
        typeBox.setSelectedIndex(0);
        descriptionTextArea.setText("");
    }
    
    private String[] populateYears() {
		int year = Calendar.getInstance().get(Calendar.YEAR);
		String [] years = new String[year-1949];
		
		for (int i = 0; i < years.length; i++) {
			years[i] = Integer.toString(year-i);
		}
		return years;
	}
    
    private String[] populateTypes() {
		String [] types = {"DVD", "BlueRay"};
		return types;
	}
    
    private String[] populateRatings() {
		String [] ratings = {"UR (Unrated)", "G", "PG", "PG-13", "R", "NC-17"};
		return ratings;
	}
    
    private String[] populateGenres() {
		String [] genres = {"Action", "Adventure", "Animation", "Biography",
							"Comedy", "Crime", "Documentary", "Drama",
							"Family", "Fantasy", "Film-Noir", "Game-Show",
							"History", "Horror", "Music", "Musical", "Mystery",
							"News", "Reality-TV", "Romance", "Sci-Fi", "Sport",
							"Talk-Show", "Thriller", "War", "Western"};
		return genres;
	}
    
}