/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;

import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author larry
 */
public class ProductDetailsView extends javax.swing.JDialog {

	// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bindButton;
    private javax.swing.JScrollPane descriptionScrollPane;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JLabel genreHeader;
    private javax.swing.JLabel genreLabel;
    private javax.swing.JLabel ratingHeader;
    private javax.swing.JLabel ratingLabel;
    private javax.swing.JButton rentButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel yearLabel;
	private ArrayList<Object> product;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Creates new form ProductDetailsView
     */
    public ProductDetailsView(java.awt.Frame parent, boolean modal, ArrayList<Object> product) {
        super(parent, modal);
        this.product = product;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        genreHeader = new javax.swing.JLabel();
        genreLabel = new javax.swing.JLabel();
        ratingHeader = new javax.swing.JLabel();
        ratingLabel = new javax.swing.JLabel();
        descriptionScrollPane = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        rentButton = new javax.swing.JButton();
        bindButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Movie Details");

        titleLabel.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText(product.get(0).toString() + " (" + product.get(4).toString() + ")");

        yearLabel.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        yearLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yearLabel.setText(product.get(3).toString());

        genreHeader.setText("Genre:");
        genreLabel.setText(product.get(1).toString());

        ratingHeader.setText("Rating:");
        ratingLabel.setText(product.get(2).toString());

        descriptionTextArea.setEditable(false);
        descriptionTextArea.setBackground(new java.awt.Color(231, 229, 229));
        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        descriptionScrollPane.setViewportView(descriptionTextArea);
        try {
        	descriptionTextArea.setText(product.get(5).toString());
        }
        catch (NullPointerException e){
        	descriptionTextArea.setText("There is no description for this movie");
        }

        rentButton.setText("Rent Movie");

        bindButton.setText("Bind Movie");
        bindButton.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                    .addComponent(yearLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(genreHeader)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(genreLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ratingHeader)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ratingLabel)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rentButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bindButton, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genreHeader)
                    .addComponent(genreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ratingHeader)
                    .addComponent(ratingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(descriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bindButton)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /*public void showDedails(ArrayList<Object> product){
    	getTitleLabel().setText(product.get(0) + " (" + product.get(4) + ")");
    	yearLabel.setText(product.get(3).toString());
    	genreLabel.setText((String) product.get(1));
    	ratingLabel.setText((String) product.get(2));
    	descriptionTextArea.setText((String) product.get(5));
    	titleLabel.validate();
    	yearLabel.validate();
    	genreLabel.validate();
    	ratingLabel.validate();
    	descriptionTextArea.validate();
    	System.out.println("inside dialog\t" + product.get(0) + " (" + product.get(4) + ")");
    }*/
}
