/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Font;
import java.awt.Frame;
import java.awt.Point;
import java.awt.event.ActionListener;
import java.awt.event.FocusListener;
import java.awt.event.ItemListener;
import java.awt.event.MouseListener;
import java.util.ArrayList;

import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author larry
 */
public class UserView extends JDialog {

    /**
     * Creates new form UserView
     */
    public UserView(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setSize(700, 600);
        this.setResizable(false);
        location = parent.getLocation();
        this.setLocation(location.x, location.y + 200);
    }
    
    public JTextField getSearchField(){
    	return searchField;
    }
    
    public JLabel getNoticeLabel(){
    	return this.noticeLabel;
    }
    
    public JButton getAddUserButton(){
    	return this.addUserButton;
    }
    
    public JRadioButton getCustomerRadio(){
    	return this.customerRadio;
    }
    
    public JRadioButton getEmployeeRadio(){
    	return this.employeeRadio;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        showDetailsLabel = new JLabel();
        searchButton = new JButton();
        noticeLabel = new JLabel();
        uTableLabel = new JLabel();
        searchField = new JTextField();
        tableScrollPane = new JScrollPane();
        usersTable = new JTable();
        searchLabel = new JLabel();
        addUserButton = new JButton();
        buttonsGroup = new javax.swing.ButtonGroup();
        customerRadio = new JRadioButton();
        employeeRadio = new JRadioButton();
        
        setTitle("Video Club");

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        usersTable = new JTable(){
          	 public boolean isCellEditable(int row, int column){  
          		    return false;  
          		  } 
        };
        
        usersTable.setModel(model);
        usersTable.setColumnSelectionAllowed(true);
        usersTable.getTableHeader().setReorderingAllowed(false);
        tableScrollPane.setViewportView(usersTable);
        usersTable.getColumnModel().getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        usersTable.getColumnModel().getColumn(0).setResizable(true);
        usersTable.getColumnModel().getColumn(1).setResizable(true);
        usersTable.getColumnModel().getColumn(2).setResizable(true);
        usersTable.getColumnModel().getColumn(3).setResizable(true);
        usersTable.getColumnModel().setColumnSelectionAllowed(false);
        usersTable.setSelectionMode(0);

        showDetailsLabel.setFont(new Font("Ubuntu", 1, 14));
        showDetailsLabel.setText("Double-click on a user to view his/her details");

        searchButton.setText("Search");
        
        noticeLabel.setFont(new Font("Ubuntu", 1, 14));
        noticeLabel.setText("There are no results matching your search criteria.");
        noticeLabel.setVisible(false);        

        uTableLabel.setFont(new Font("Ubuntu", 3, 24)); // NOI18N
        uTableLabel.setHorizontalAlignment(SwingConstants.CENTER);
        uTableLabel.setText("Customers List");

        searchLabel.setText("Search By Email:");

        addUserButton.setText("Add New User");
        
        buttonsGroup.add(customerRadio);
        customerRadio.setText("Customer");
        customerRadio.setSelected(true);
        
        buttonsGroup.add(employeeRadio);
        employeeRadio.setText("Employee");
        
        userProfile = "customer";

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableScrollPane)
                    .addComponent(uTableLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addUserButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchLabel)
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(customerRadio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(employeeRadio))
                                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(noticeLabel)))
                            .addComponent(showDetailsLabel))
                        .addGap(0, 151, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(uTableLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showDetailsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchLabel)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUserButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(customerRadio)
                    .addComponent(employeeRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noticeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }
    
    public void addButtonsGroupItemStateChanged(ItemListener buttonsGroupOption) {
        customerRadio.addItemListener(buttonsGroupOption);
        employeeRadio.addItemListener(buttonsGroupOption);
    }
    
    public void addSubmitSearchListener(ActionListener search) {
        searchButton.addActionListener(search);
    }
    
    public void addSearchFieldFocusGained(FocusListener searchFocus) {
        searchField.addFocusListener(searchFocus);
    }
    
    public void addNewUserListener(ActionListener addMovie) {
        addUserButton.addActionListener(addMovie);
    }    
    
    public void addMouseListener(MouseListener tableDoubleClick){
    	usersTable.addMouseListener(tableDoubleClick);
    }
    
    public String getUserProfile(){
    	return userProfile;
    }
    
    public void setUserProfile(String profile){
    	userProfile = profile;
    }
    
    public void addOne(ArrayList<Object> oneUser) {
		row[0] = oneUser.get(2);
        row[1] = oneUser.get(3);
        row[2] = oneUser.get(4);
        row[3] = oneUser.get(0);
        model.addRow(row);
	}
        
    public void showAll(ArrayList<Object> allProducts) {
    	int tableSize = model.getRowCount();
    	
    	for (int i = 0; i < tableSize; i++) {
    		model.removeRow(tableSize-i-1);
    	}
    	
    	for (int i = 0; i < allProducts.size(); i += 4) {
    		row[0] = allProducts.get(i);
    		row[1] = allProducts.get(i+1);
    		row[2] = allProducts.get(i+2);
    		row[3] = allProducts.get(i+3);
    		model.addRow(row);
    	}
    }

	public void updateRow(int row, ArrayList<Object> user) {
		usersTable.setValueAt(user.get(2), row, 0);
		usersTable.setValueAt(user.get(3), row, 1);
		usersTable.setValueAt(user.get(4), row, 2);
		usersTable.setValueAt(user.get(6), row, 3);	
	}
    
    // Variables declaration - do not modify
    private JButton addUserButton;
    private JLabel showDetailsLabel;
    private JTable usersTable;
    private JLabel noticeLabel;
    private JButton searchButton;
    private JTextField searchField;
    private JLabel searchLabel;
    private JScrollPane tableScrollPane;
    private JLabel uTableLabel;
    
    private String[] columns = {"Name", "Email", "Phone", "Profile"};
	private Object[] row = new Object[5];	    
	private DefaultTableModel model = new DefaultTableModel(columns, 0);
    
	private ButtonGroup buttonsGroup;
	private JRadioButton customerRadio;
	private JRadioButton employeeRadio;
	
	private String userProfile;
	
    private Point location;
    // End of variables declaration
}
