/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Font;
import java.awt.Frame;
import java.awt.Point;
import java.awt.event.ActionListener;
import java.awt.event.FocusListener;
import java.awt.event.MouseListener;
import java.util.ArrayList;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author larry
 */
public class UserView extends JDialog {

    /**
     * Creates new form UserView
     */
    public UserView(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setSize(800, 600);
        this.setResizable(false);
        location = parent.getLocation();
        this.setLocation(location.x + 140, location.y + 140);
    }
    
    public JTextField getSearchField(){
    	return searchField;
    }
    
    public JLabel getNoticeLabel(){
    	return this.noticeLabel;
    }
    
    public JButton getAddUserButton(){
    	return this.addUserButton;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        showDetailsLabel = new JLabel();
        searchButton = new JButton();
        noticeLabel = new JLabel();
        uTableLabel = new JLabel();
        searchField = new JTextField();
        tableScrollPane = new JScrollPane();
        usersTable = new JTable();
        searchLabel = new JLabel();
        addUserButton = new JButton();
        
        setTitle("Video Club");

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        usersTable = new JTable(){
          	 public boolean isCellEditable(int row, int column){  
          		    return false;  
          		  } 
        };
        
        usersTable.setModel(model);
        usersTable.setColumnSelectionAllowed(true);
        usersTable.getTableHeader().setReorderingAllowed(false);
        tableScrollPane.setViewportView(usersTable);
        usersTable.getColumnModel().getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        usersTable.getColumnModel().getColumn(0).setResizable(true);
        usersTable.getColumnModel().getColumn(1).setResizable(true);
        usersTable.getColumnModel().getColumn(2).setResizable(true);
        usersTable.getColumnModel().getColumn(3).setResizable(true);
        usersTable.getColumnModel().setColumnSelectionAllowed(false);
        usersTable.setSelectionMode(0);

        showDetailsLabel.setFont(new Font("Ubuntu", 1, 14));
        showDetailsLabel.setText("Double-click on a user to view his/her details");

        searchButton.setText("Search");
        
        noticeLabel.setFont(new Font("Ubuntu", 1, 14));
        noticeLabel.setText("There are no results matching your search criteria.");
        noticeLabel.setVisible(false);        

        uTableLabel.setFont(new Font("Ubuntu", 3, 18)); // NOI18N
        uTableLabel.setHorizontalAlignment(SwingConstants.CENTER);
        uTableLabel.setText("Customers List");

        searchLabel.setText("Search By Email:");

        addUserButton.setFont(new Font("Ubuntu", 3, 15)); // NOI18N
        addUserButton.setText("Add New User");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(tableScrollPane)
                    .addComponent(uTableLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addUserButton)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchLabel)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(searchButton, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(searchField, GroupLayout.PREFERRED_SIZE, 263, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(noticeLabel)
                                .addGap(0, 163, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(showDetailsLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(uTableLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showDetailsLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableScrollPane, GroupLayout.PREFERRED_SIZE, 359, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(searchLabel)
                    .addComponent(searchField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUserButton))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noticeLabel, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

    }// </editor-fold>
    
    
    public void addSubmitSearchListener(ActionListener search) {
        searchButton.addActionListener(search);
    }
    
    public void addSearchFieldFocusGained(FocusListener searchFocus) {
        searchField.addFocusListener(searchFocus);
    }
    
    public void addNewUserListener(ActionListener addMovie) {
        addUserButton.addActionListener(addMovie);
    }    
    
    public void addMouseListener(MouseListener tableDoubleClick){
    	usersTable.addMouseListener(tableDoubleClick);
    }
    
    public void addOne(ArrayList<Object> oneProduct) {
		row[0] = oneProduct.get(0);
        row[1] = oneProduct.get(1);
        row[2] = oneProduct.get(2);
        row[3] = oneProduct.get(3);
        model.addRow(row);
	}
        
    public void showAll(ArrayList<Object> allProducts) {
    	int tableSize = model.getRowCount();
    	
    	for (int i = 0; i < tableSize; i++) {
    		model.removeRow(tableSize-i-1);
    	}
    	
    	for (int i = 0; i < allProducts.size(); i += 4) {
    		row[0] = allProducts.get(i);
    		row[1] = allProducts.get(i+1);
    		row[2] = allProducts.get(i+2);
    		row[3] = allProducts.get(i+3);
    		model.addRow(row);
    	}
    }

	public void updateRow(int row, ArrayList<Object> product) {
		usersTable.setValueAt(product.get(0), row, 0);
		usersTable.setValueAt(product.get(1), row, 1);
		usersTable.setValueAt(product.get(2), row, 2);
		usersTable.setValueAt(product.get(3), row, 3);	
	}
    
    // Variables declaration - do not modify
    private JButton addUserButton;
    private JLabel showDetailsLabel;
    private JTable usersTable;
    private JLabel noticeLabel;
    private JButton searchButton;
    private JTextField searchField;
    private JLabel searchLabel;
    private JScrollPane tableScrollPane;
    private JLabel uTableLabel;
    private String[] columns = {"Name", "Email", "Phone", "Profile"};
	private Object[] row = new Object[5];	    
	private DefaultTableModel model = new DefaultTableModel(columns, 0);
    
    private Point location;
    // End of variables declaration
}
