/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package EmployeeView;

import java.util.ArrayList;

import javax.swing.JLabel;
import javax.swing.JTextField;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;

/**
 *
 * @author larry
 */
public class CustomerDetailsView extends javax.swing.JDialog {

	// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bindButton;
    private javax.swing.JLabel firstName;
    private javax.swing.JLabel fnameLabel;
    private javax.swing.JLabel lnameHeader;
    private javax.swing.JLabel lnameLabel;
    private javax.swing.JButton rentButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel yearLabel;
	private ArrayList<Object> product;
	private JLabel addressHeader;
	private JLabel emailHeader;
	private JLabel phoneHeader;
	private JLabel zipcodeHeader;
	private JLabel addressLabel;
	private JLabel emailLabel;
	private JLabel phoneLabel;
	private JLabel zipcodeLabel;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Creates new form ProductDetailsView
     */
    public CustomerDetailsView(java.awt.Frame parent, boolean modal, ArrayList<Object> product) {
        super(parent, modal);
        setResizable(false);
        this.product = product;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        firstName = new javax.swing.JLabel();
        fnameLabel = new javax.swing.JLabel();
        lnameHeader = new javax.swing.JLabel();
        lnameLabel = new javax.swing.JLabel();
        rentButton = new javax.swing.JButton();
        rentButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	}
        });
        bindButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Customer Details");
        
      

        titleLabel.setFont(new Font("Dialog", Font.BOLD | Font.ITALIC, 16)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        /*
         * Ta stoixeia antlountai apo ton pinaka customers
         * Allagi setText pros antistoixes tou customer
         * */
        
        String title = product.get(0).toString() + " (" + product.get(4).toString() + ")";
        titleLabel.setText("Customer Details");

        yearLabel.setFont(new Font("Dialog", Font.ITALIC, 15)); // NOI18N
        
        yearLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yearLabel.setText("Details for: <dynamic>");

        firstName.setText("First name");
        fnameLabel.setText("<dynamic>");

        lnameHeader.setText("Last Name");
        lnameLabel.setText(product.get(2).toString());
      
        addressHeader = new JLabel();
        addressHeader.setText("Address");
        
        emailHeader = new JLabel();
        emailHeader.setText("Email");
        
        phoneHeader = new JLabel();
        phoneHeader.setText("Phone");
        
        zipcodeHeader = new JLabel();
        zipcodeHeader.setText("Zip Code");
        
        addressLabel = new JLabel();
        addressLabel.setText("<dynamic>");
        
        emailLabel = new JLabel();
        emailLabel.setText("<dynamic>");
        
        phoneLabel = new JLabel();
        phoneLabel.setText("<dynamic>");
        
        zipcodeLabel = new JLabel();
        zipcodeLabel.setText("<dynamic>");
        
        rentButton.setText("Delete Customer");

        bindButton.setText("Edit Customer");
      

        /*
         * 
         *Methodoi tou menou Customer Details
         * 
         * 
        public void editCustomer(){

        }

        public void deleteCustomer(){

        }
        
        */

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(yearLabel, GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        				.addComponent(titleLabel, GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        				.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(firstName)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(fnameLabel)
        							.addGap(112))
        						.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        							.addComponent(addressHeader, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(addressLabel, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
        							.addGap(112))
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(lnameHeader)
        									.addPreferredGap(ComponentPlacement.RELATED)
        									.addComponent(lnameLabel))
        								.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        									.addGroup(layout.createSequentialGroup()
        										.addComponent(emailHeader, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
        										.addPreferredGap(ComponentPlacement.RELATED)
        										.addComponent(emailLabel, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE))
        									.addGroup(layout.createSequentialGroup()
        										.addComponent(phoneHeader, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
        										.addPreferredGap(ComponentPlacement.RELATED)
        										.addComponent(phoneLabel, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE))
        									.addGroup(layout.createSequentialGroup()
        										.addComponent(zipcodeHeader, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
        										.addPreferredGap(ComponentPlacement.RELATED)
        										.addComponent(zipcodeLabel, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE))))
        							.addGap(112)))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(bindButton)
        						.addComponent(rentButton))))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(titleLabel, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(yearLabel, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(firstName)
        				.addComponent(fnameLabel, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lnameHeader)
        				.addComponent(lnameLabel, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(addressHeader)
        						.addComponent(addressLabel, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(emailHeader)
        						.addComponent(emailLabel, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(phoneHeader)
        						.addComponent(phoneLabel, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(zipcodeHeader)
        						.addComponent(zipcodeLabel, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(rentButton)
        					.addGap(29)
        					.addComponent(bindButton)))
        			.addContainerGap(19, Short.MAX_VALUE))
        );
        
        
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
}
