/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package EmployeeView;

import java.awt.event.ActionListener;
import java.util.Calendar;

import javax.swing.*;

import dao.ProductDao;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;



@SuppressWarnings({ "unchecked", "rawtypes" })
public class ManageCustomerView extends JDialog {
	
    private JLabel headerLabel;
    private JButton resetButton;
    private JButton submitButton;
    private JTextField fnameField;
    private JLabel titleLabel;
    private JTextField lnameField;
    private JTextField emailField;
    private JTextField phoneField;
    private JLabel lblPhone;
    private JLabel lblAddress;
    private JTextField addressField;
    private JLabel lblZipCode;
    private JTextField zipField;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Creates new form ManageCustomerView
     */
    public ManageCustomerView(java.awt.Frame parent, boolean modal, ProductDao model) {
        //super(parent, modal);
        initComponents();
    }
    
    //Methods to return the text of the fields 
    public JTextField getFnameField() {
		return fnameField;
	}

	public JTextField getLnameField() {
		return lnameField;
	}

	public JTextField getEmailField() {
		return emailField;
	}

	public JTextField getPhoneField() {
		return phoneField;
	}

	public JTextField getAddressField() {
		return addressField;
	}

	public JTextField getZipField() {
		return zipField;
	}
	

	public void addSubmitButtonListener(ActionListener submit) {
        submitButton.addActionListener(submit);
    }
    
    public void addResetButtonListener(ActionListener reset) {
        resetButton.addActionListener(reset);
    }
    
    public void reset() {
    	fnameField.setText("");
    	lnameField.setText("");
    	emailField.setText("");
    	phoneField.setText("");
    	addressField.setText("");
    	zipField.setText("");
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        fnameField = new JTextField();
        titleLabel = new JLabel();
        headerLabel = new JLabel();
        resetButton = new JButton();
        submitButton = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Customer");

        titleLabel.setText("Name");

        headerLabel.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        headerLabel.setHorizontalAlignment(SwingConstants.CENTER);
        headerLabel.setText("Add New Customer");

        resetButton.setText("Reset");

        submitButton.setText("Add Customer");
        
        JLabel lblSurname = new JLabel("Surname");
        
        lnameField = new JTextField();
        lnameField.setColumns(10);
        
        JLabel lblEmail = new JLabel("Email");
        
        emailField = new JTextField();
        emailField.setColumns(10);
        
        phoneField = new JTextField();
        phoneField.setColumns(10);
        
        lblPhone = new JLabel("Phone");
        
        lblAddress = new JLabel("Address");
        
        addressField = new JTextField();
        addressField.setColumns(10);
        
        lblZipCode = new JLabel("Zip Code");
        
        zipField = new JTextField();
        zipField.setColumns(10);
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addContainerGap(84, Short.MAX_VALUE)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(headerLabel, GroupLayout.PREFERRED_SIZE, 490, GroupLayout.PREFERRED_SIZE)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addComponent(titleLabel)
        					.addGap(19)
        					.addComponent(fnameField, GroupLayout.PREFERRED_SIZE, 190, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(lblAddress)
        					.addGap(10)
        					.addComponent(addressField, GroupLayout.PREFERRED_SIZE, 187, GroupLayout.PREFERRED_SIZE))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addComponent(lblEmail)
        					.addGap(22)
        					.addComponent(emailField, GroupLayout.PREFERRED_SIZE, 190, GroupLayout.PREFERRED_SIZE))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addComponent(lblPhone)
        					.addGap(16)
        					.addComponent(phoneField, GroupLayout.PREFERRED_SIZE, 190, GroupLayout.PREFERRED_SIZE))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addComponent(lblSurname)
        					.addGap(4)
        					.addComponent(lnameField, GroupLayout.PREFERRED_SIZE, 190, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(lblZipCode)
        					.addGap(10)
        					.addComponent(zipField, GroupLayout.PREFERRED_SIZE, 184, GroupLayout.PREFERRED_SIZE))
        				.addGroup(Alignment.TRAILING, groupLayout.createSequentialGroup()
        					.addComponent(submitButton, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
        					.addGap(53)
        					.addComponent(resetButton, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
        					.addGap(190))))
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(11)
        			.addComponent(headerLabel)
        			.addGap(29)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(3)
        					.addComponent(titleLabel))
        				.addComponent(fnameField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(3)
        					.addComponent(lblAddress))
        				.addComponent(addressField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(3)
        					.addComponent(lblSurname))
        				.addComponent(lnameField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(3)
        					.addComponent(lblZipCode))
        				.addComponent(zipField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(lblEmail)
        				.addComponent(emailField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(19)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(3)
        					.addComponent(lblPhone))
        				.addComponent(phoneField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(42)
        			.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(submitButton)
        				.addComponent(resetButton))
        			.addGap(36))
        );
        getContentPane().setLayout(groupLayout);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
   
    
    /*
     * Se periptwsi eisagogis kainouriou xristi ektos apo customer
     * 
    private String[] populateTypes() {
		String [] types = {"Employee", "Customer"};
		return types;
	}
	*/
     
   
}